services:
  fitbit2garmin:
    user: "${UID}:${GID}"
    build: .
    container_name: fitbit2garmin
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - CONFIG_FILE=/app/data/config.yaml
      - GARTH_HOME=/app/data/garth
